# Generated by Django 5.2.7 on 2025-10-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('game_date', models.DateField()),
                ('spread', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('moneyline', models.CharField(max_length=100)),
                ('prior_week_winning_margin', models.IntegerField()),
                ('travel_miles', models.IntegerField()),
            ],
        ),
    ]
