# Generated by Django 5.2.7 on 2025-10-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='prior_week_winning_margin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='total',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='travel_miles',
            field=models.CharField(max_length=100),
        ),
    ]
