# Generated by Django 5.2.7 on 2025-10-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_note_prior_week_winning_margin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='moneyline',
        ),
        migrations.RemoveField(
            model_name='note',
            name='prior_week_winning_margin',
        ),
        migrations.RemoveField(
            model_name='note',
            name='spread',
        ),
        migrations.RemoveField(
            model_name='note',
            name='total',
        ),
        migrations.AddField(
            model_name='note',
            name='days_between_games',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='home_away',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='margin',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='opponent',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='opponent_score',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='team_score',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='game_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='travel_miles',
            field=models.CharField(max_length=200),
        ),
    ]
